### ISSUE TITLE
Modify template of outcome description

### ISSUE THREAD

**Issue by Cristrinaranjus** [CCOMS-UAM/ecs-data#13]
https://github.com/CCOMS-UAM/ecs-data/blob/9c2e0e31b307f777398d5b0bb1136317fbf2d098/inst/rmarkdown/templates/description_variable/skeleton/skeleton.Rmd#L245

The template needs to be modified, as it appears "variable ID to be included for Cohort 2019" when it should be "for Cohort 2011".

Thanks in advance :)

**Comment by DaniMori** [comment]
Solved in 8c09ec6cd18f60118f9ca2ab403316e1c0bac36f
